version: '3'

dotenv: ['.env']

tasks:
  dev:
    desc: Dev server
    cmds:
      - air

  build:
    desc: Build app
    cmds:
      - go build -o bin/server ./cmd/server/main.go

  db:migrate:
    cmds:
      - goose -dir db/postgres/migrations postgres "$DB_POSTGRES_URL" up
      # - goose -dir db/clickhouse/migrations clickhouse "$DB_CLICKHOUSE_URL" up

  db:migrate:down:
    cmds:
      - goose -dir db/postgres/migrations postgres "$DB_POSTGRES_URL" down
      # - goose -dir db/clickhouse/migrations clickhouse "$DB_CLICKHOUSE_URL" up

  test:
    desc: Run all unit tests
    cmds:
      - go test -v ./...

  lint:
     desc: Run linter
     cmds:
       - golangci-lint run

  format:
     desc: Run formater
     cmds:
       - golangci-lint fmt

  infra:up:
    cmds:
      - docker compose up -d

  infra:down:
    cmds:
      - docker compose down

  infra:logs:
    cmds:
      - docker compose logs -f
