version: '3'

tasks:
  dev:
    desc: Dev server
    cmds:
      - air

  build:
    desc: Build app
    cmds:
      - go build -o bin/server ./cmd/server/main.go

  test:
    desc: Run all unit tests
    cmds:
      - go test -v ./...

  lint:
     desc: Run linter
     cmds:
       - golangci-lint run

  format:
     desc: Run formater
     cmds:
       - golangci-lint fmt
